# Generated by Django 2.2.7 on 2020-01-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltests',
            name='client_code',
            field=models.CharField(db_column='Client_code', max_length=100, primary_key=True, serialize=False),
        ),
    ]
