# Generated by Django 2.2.7 on 2019-12-20 09:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adelphoi_Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.IntegerField(db_column='program')),
                ('program_name', models.CharField(db_column='program_name', max_length=100)),
                ('gender', models.IntegerField(db_column='gender')),
                ('gender_name', models.CharField(db_column='gender_name', max_length=20)),
                ('level_of_care', models.IntegerField(db_column='level_of_care')),
                ('level_names', models.CharField(db_column='level_names', max_length=100)),
                ('location', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(db_column='location'), size=None)),
                ('location_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(db_column='location_names', max_length=100), size=None)),
                ('facility_type', models.IntegerField(db_column='facility_type')),
                ('facility_names', models.CharField(db_column='facility_names', max_length=100)),
                ('program_model_suggested', models.CharField(db_column='program_model_suggested', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='ade_mapping',
            name='level_name',
            field=models.CharField(db_column='level_name', default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ade_mapping',
            name='location_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(db_column='location_name', max_length=100), default=1, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ade_mapping',
            name='program_name',
            field=models.CharField(db_column='program_name', default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modeltests',
            name='Program_Completion',
            field=models.IntegerField(choices=[(0, 'no'), (1, 'yes')], db_column='Program Completion', null=True),
        ),
        migrations.AddField(
            model_name='modeltests',
            name='Returned_to_Care',
            field=models.IntegerField(choices=[(0, 'no'), (1, 'yes')], db_column='Returned_to_Care', null=True),
        ),
        migrations.AddField(
            model_name='modeltests',
            name='client_selected_facility',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modeltests',
            name='client_selected_level',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modeltests',
            name='client_selected_locations',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modeltests',
            name='client_selected_program',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modeltests',
            name='facility_type',
            field=models.IntegerField(db_column='facility_pred', default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='CYF_code',
            field=models.IntegerField(choices=[(1, 'CYF'), (2, 'Juvenile Justice')], db_column='CYF_code'),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='FAST_CaregiverAdvocacyScore',
            field=models.FloatField(blank=True, db_column='FAST_CaregiverAdvocacyScore'),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='FAST_FamilyTogetherScore',
            field=models.FloatField(blank=True, db_column='FAST_FamilyTogetherScore'),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='RefSourceCode',
            field=models.IntegerField(choices=[(1, 'Adams'), (2, 'Allegheny'), (3, 'Beaver'), (4, 'Bedford'), (5, 'Berks'), (6, 'Blair'), (7, 'Bucks'), (8, 'Butler'), (9, 'Cambria'), (10, 'Centre'), (11, 'Chester'), (12, 'Cumberland'), (13, 'Dauphin'), (14, 'Delaware'), (15, 'Erie'), (16, 'Fayette'), (17, 'Franklin'), (18, 'Huntingdon'), (19, 'Juniata'), (20, 'Kent'), (21, 'Lackawanna'), (22, 'Lancaster'), (23, 'Lebanon'), (24, 'Lehigh'), (25, 'Lycoming'), (26, 'Monroe'), (27, 'Montgomery'), (28, 'Montour'), (29, 'Northumberland'), (30, 'Perry'), (31, 'Philadelphia'), (32, 'Pike'), (34, 'Snyder'), (35, 'Tioga'), (36, 'Washington'), (37, 'Westmoreland'), (38, 'York'), (39, 'Armstrong'), (40, 'Columbia'), (41, 'Crawford'), (42, 'Cayahoga OH'), (43, 'Franklin OH'), (44, 'Greene'), (45, 'Indiana'), (46, 'Lawrence'), (48, 'Mckean'), (49, 'Mercer'), (50, 'outside tri-county'), (51, 'Northampton'), (52, 'Pike'), (53, 'Schukill'), (54, 'Somerset'), (55, 'Union'), (56, 'Venango'), (57, 'Fulton'), (59, 'WV'), (60, 'SE PA')], db_column='RefSourceCode'),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='Screening_tool_Trauma',
            field=models.FloatField(blank=True, db_column='Screening_tool_Trauma'),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='abuse_neglect',
            field=models.FloatField(choices=[(0, 'no'), (1, 'yes')], db_column='abuse_neglect'),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='cans_CareGiverStrengths',
            field=models.FloatField(blank=True, db_column='CANS_CareGiverStrengths'),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='cans_Culture',
            field=models.FloatField(blank=True, db_column='CANS_Culture'),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='cans_LifeFunctioning',
            field=models.FloatField(blank=True, db_column='CANS_LifeFunctioning'),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='cans_Trauma_Exp',
            field=models.FloatField(blank=True, db_column='CANS_Trauma_Exp'),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='cans_YouthBehavior',
            field=models.FloatField(blank=True, db_column='CANS_YouthBehavior'),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='cans_YouthRisk',
            field=models.FloatField(blank=True, db_column='CANS_YouthRisk'),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='cans_YouthStrengths',
            field=models.FloatField(blank=True, db_column='CANS_YouthStrengths'),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='client_self_harm',
            field=models.FloatField(blank=True, db_column='Client_self_harm'),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='family_support',
            field=models.FloatField(db_column='family_support', null=True),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='fire_setting',
            field=models.FloatField(db_column='fire_setting', null=True),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='level_of_aggression',
            field=models.FloatField(db_column='level_of_aggression', null=True),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='yls_Attitude_Score',
            field=models.FloatField(blank=True, db_column='YLS_Attitude_Score'),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='yls_Edu_Employ_Score',
            field=models.FloatField(blank=True, db_column='YLS_Edu_Employ_Score'),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='yls_FamCircumstances_Score',
            field=models.FloatField(blank=True, db_column='YLS_FamCircumstances_Score'),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='yls_Leisure_Score',
            field=models.FloatField(blank=True, db_column='YLS_Leisure_Score'),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='yls_Peer_Score',
            field=models.FloatField(blank=True, db_column='YLS_Peer_Score'),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='yls_Personality_Score',
            field=models.FloatField(blank=True, db_column='YLS_Personality_Score'),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='yls_PriorCurrentOffenses_Score',
            field=models.FloatField(blank=True, db_column='YLS_PriorCurrentOffenses_Score'),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='yls_Subab_Score',
            field=models.FloatField(blank=True, db_column='YLS_Subab_Score'),
        ),
    ]
