# Generated by Django 2.2.7 on 2019-11-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map_Adelphoi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.IntegerField(db_column='program')),
                ('gender', models.IntegerField(db_column='gender')),
                ('level_of_care', models.IntegerField(db_column='level_of_care')),
                ('location', models.IntegerField(db_column='location')),
            ],
        ),
    ]
