# Generated by Django 2.2.7 on 2019-12-04 08:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ade_mapping',
            name='location_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(db_column='location_name', max_length=100), default=1, size=None),
            preserve_default=False,
        ),
    ]
