# Generated by Django 2.2.7 on 2019-11-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltests',
            name='confidence',
            field=models.IntegerField(db_column='Confidence', default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='hist_of_prior_program_SAO',
            field=models.IntegerField(db_column='Hist_of_prior_program_SAO'),
        ),
    ]
