# Generated by Django 2.2.7 on 2019-12-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0002_auto_20191220_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltests',
            name='Program_Completion',
            field=models.IntegerField(choices=[(0, 'no'), (1, 'yes')], db_column='Program Completion', default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='Returned_to_Care',
            field=models.IntegerField(choices=[(0, 'no'), (1, 'yes')], db_column='Returned_to_Care', default=0),
            preserve_default=False,
        ),
    ]
