# Generated by Django 2.2.7 on 2020-01-02 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0002_auto_20200102_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adelphoi_mapping',
            name='location',
        ),
    ]
