# Generated by Django 2.2.7 on 2019-11-25 05:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0002_auto_20191124_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltests',
            name='modified_date',
            field=models.DateTimeField(db_column='Modified_Date', default=datetime.datetime(2019, 11, 25, 10, 52, 30, 797194)),
        ),
    ]
