# Generated by Django 2.2.7 on 2020-01-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0002_auto_20200106_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltests',
            name='client_code',
            field=models.IntegerField(db_column='Client_code', primary_key=True, serialize=False),
        ),
    ]
