# Generated by Django 2.2.7 on 2019-11-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0003_modeltests_modified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltests',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, db_column='Modified_Date'),
        ),
    ]
