# Generated by Django 2.2.7 on 2019-12-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0003_ade_mapping_program_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ade_mapping',
            name='level_name',
            field=models.CharField(db_column='level_name', default=1, max_length=100),
            preserve_default=False,
        ),
    ]
