# Generated by Django 2.2.7 on 2020-01-02 05:50

import array_field_select.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0003_remove_adelphoi_mapping_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='adelphoi_mapping',
            name='location',
            field=array_field_select.fields.ArrayField(base_field=models.IntegerField(db_column='location'), default=1, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adelphoi_mapping',
            name='location_names',
            field=array_field_select.fields.ArrayField(base_field=models.CharField(db_column='location_names', max_length=100), default=1, size=None),
            preserve_default=False,
        ),
    ]
