# Generated by Django 2.2.7 on 2019-12-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0003_auto_20191223_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltests',
            name='RefSourceCode',
            field=models.IntegerField(choices=[(1, 'Adams'), (2, 'Allegheny'), (3, 'Beaver'), (4, 'Bedford'), (5, 'Berks'), (6, 'Blair'), (7, 'Bucks'), (8, 'Butler'), (9, 'Cambria'), (10, 'Centre'), (11, 'Chester'), (12, 'Cumberland'), (13, 'Dauphin'), (14, 'Delaware'), (15, 'Erie'), (16, 'Fayette'), (17, 'Franklin'), (18, 'Huntingdon'), (19, 'Juniata'), (20, 'Kent'), (21, 'Lackawanna'), (22, 'Lancaster'), (23, 'Lebanon'), (24, 'Lehigh'), (25, 'Lycoming'), (26, 'Monroe'), (27, 'Montgomery'), (28, 'Montour'), (29, 'Northumberland'), (30, 'Perry'), (31, 'Philadelphia'), (32, 'Pike'), (34, 'Snyder'), (35, 'Tioga'), (36, 'Washington'), (37, 'Westmoreland'), (38, 'York'), (39, 'Armstrong'), (40, 'Columbia'), (41, 'Crawford'), (42, 'Cayahoga OH'), (43, 'Franklin OH'), (44, 'Greene'), (45, 'Indiana'), (46, 'Lawrence'), (47, 'MH'), (48, 'Mckean'), (49, 'Mercer'), (50, 'outside tri-county'), (51, 'Northampton'), (52, 'Pike'), (53, 'Schukill'), (54, 'Somerset'), (55, 'Union'), (56, 'Venango'), (57, 'Fulton'), (59, 'WV'), (60, 'SE PA')], db_column='RefSourceCode'),
        ),
    ]
