# Generated by Django 2.2.7 on 2019-12-05 08:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0004_ade_mapping_level_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltests',
            name='program',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(db_column='Program'), size=None),
        ),
    ]
