# Generated by Django 2.2.7 on 2020-01-08 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0004_mapping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mapping',
        ),
    ]
