# Generated by Django 2.2.7 on 2019-12-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0004_auto_20191225_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltests',
            name='age',
            field=models.IntegerField(db_column='Age', null=True),
        ),
    ]
