# Generated by Django 2.2.7 on 2020-01-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0004_auto_20200102_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='adelphoi_mapping',
            name='program_type',
            field=models.CharField(db_column='program_type', default=1, max_length=100),
            preserve_default=False,
        ),
    ]
