# Generated by Django 2.2.7 on 2019-11-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0005_auto_20191125_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltests',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Female'), (2, 'Male')], db_column='Gender'),
        ),
    ]
