# Generated by Django 2.2.7 on 2019-12-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0005_auto_20191205_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltests',
            name='program',
            field=models.IntegerField(db_column='Program'),
        ),
    ]
