# Generated by Django 2.2.7 on 2019-12-25 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0005_modeltests_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeltests',
            name='age',
        ),
    ]
