# Generated by Django 2.2.7 on 2020-01-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0006_modeltests_referred_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltests',
            name='model_program',
            field=models.IntegerField(db_column='Model_Program', default=1),
            preserve_default=False,
        ),
    ]
