# Generated by Django 2.2.7 on 2020-01-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0006_album_musician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltests',
            name='ageAtEnrollStart',
            field=models.IntegerField(blank=True, db_column='AgeAtEnrollStart'),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='ageAtEpisodeStart',
            field=models.IntegerField(blank=True, db_column='AgeAtEpisodeStart'),
        ),
    ]
