# Generated by Django 2.2.7 on 2019-12-06 08:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0006_auto_20191205_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adelphoi_Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.IntegerField(db_column='program')),
                ('program_name', models.CharField(db_column='program_name', max_length=100)),
                ('gender', models.IntegerField(db_column='gender')),
                ('gender_name', models.CharField(db_column='gender_name', max_length=20)),
                ('level_of_care', models.IntegerField(db_column='level_of_care')),
                ('level_names', models.CharField(db_column='level_names', max_length=100)),
                ('location', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(db_column='location'), size=None)),
                ('location_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(db_column='location_names', max_length=100), size=None)),
                ('facility_type', models.IntegerField(db_column='facility_type')),
                ('facility_names', models.CharField(db_column='facility_names', max_length=100)),
            ],
        ),
    ]
