# Generated by Django 2.2.7 on 2019-12-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0007_modeltests_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodels',
            name='Exclusionary_Criteria',
            field=models.BooleanField(db_column='Exclusionary_Criteria', default=False),
        ),
    ]
