# Generated by Django 2.2.7 on 2020-01-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0007_modeltests_model_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltests',
            name='model_program',
            field=models.CharField(db_column='Model_Program', max_length=100),
        ),
    ]
