# Generated by Django 2.2.7 on 2019-12-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0007_adelphoi_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltests',
            name='client_selected_program',
            field=models.CharField(choices=[(1, 'substance abuse'), (2, 'sex offender'), (3, 'intensive supervision')], default='null', max_length=10),
            preserve_default=False,
        ),
    ]
