# Generated by Django 2.2.7 on 2020-01-12 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0007_auto_20200112_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeltests',
            name='ageAtEnrollStart',
        ),
    ]
