# Generated by Django 2.2.7 on 2020-01-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0008_remove_modeltests_ageatenrollstart'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltests',
            name='ageAtEnrollStart',
            field=models.IntegerField(blank=True, db_column='AgeAtEnrollStart', default=1),
            preserve_default=False,
        ),
    ]
