# Generated by Django 2.2.7 on 2019-12-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0009_auto_20191211_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltests',
            name='facility_type',
            field=models.IntegerField(db_column='facility_pred', default=1),
            preserve_default=False,
        ),
    ]
