# Generated by Django 2.2.7 on 2020-01-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0009_modeltests_ageatenrollstart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltests',
            name='abuse_neglect',
            field=models.FloatField(blank=True, choices=[(0, 'no'), (1, 'yes')], db_column='abuse_neglect'),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='alcohol_Use',
            field=models.IntegerField(blank=True, choices=[(0, 'no'), (1, 'yes')], db_column='Alcohol_Use'),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='death_Caregiver',
            field=models.IntegerField(blank=True, choices=[(0, 'no'), (1, 'yes')], db_column='Death_Caregiver'),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='death_Silblings',
            field=models.IntegerField(blank=True, choices=[(0, 'no'), (1, 'yes')], db_column='Death Silblings'),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='drug_Use',
            field=models.IntegerField(blank=True, choices=[(0, 'no'), (1, 'yes')], db_column='Drug_Use'),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='english_second_lang',
            field=models.IntegerField(blank=True, choices=[(0, 'not at all'), (1, 'very little'), (2, 'average'), (3, 'very well')], db_column='english_second_lang'),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='incarcerated_siblings',
            field=models.IntegerField(blank=True, choices=[(0, 'no'), (1, 'yes')], db_column='Incarcerated_siblings'),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='primaryRaceCode',
            field=models.IntegerField(blank=True, choices=[(1, 'caucasian'), (2, 'African American'), (3, 'Hispanic'), (4, 'Others')], db_column='PrimaryRacecode'),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='referred_program',
            field=models.CharField(blank=True, choices=[('ISM', 'ISM'), ('ISF', 'ISF'), ('MHFO', 'MHFO'), ('SUBAB', 'SUBAB'), ('DIAGNOSTIC', 'DIAGNOSTIC'), ('SEXOF-MH', 'SEXOF-MH'), ('SEXOF-SECURE', 'SEXOF-SECURE'), ('SEXOF', 'SEXOF'), ('ENHANCED', 'ENHANCED'), ('SECURE-MALE', 'SECURE-MALE'), ('SECURE-FEMALE', 'SECURE-FEMALE'), ('INDEPENDENT LIVING', 'INDEPENDENT LIVING')], db_column='referred_program', max_length=100),
        ),
    ]
