# Generated by Django 2.2.7 on 2019-12-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0010_modeltests_facility_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltests',
            name='family_support',
            field=models.FloatField(db_column='family_support', null=True),
        ),
    ]
