# Generated by Django 2.2.7 on 2020-01-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0012_auto_20200112_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltests',
            name='FAST_CaregiverAdvocacyScore',
            field=models.FloatField(blank=True, db_column='FAST_CaregiverAdvocacyScore', null=True),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='FAST_FamilyTogetherScore',
            field=models.FloatField(blank=True, db_column='FAST_FamilyTogetherScore', null=True),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='enrollStart_date',
            field=models.DateField(blank=True, db_column='enrollStart_date', null=True),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='type_of_drugs',
            field=models.TextField(blank=True, db_column='type_of_drugs', null=True),
        ),
    ]
