# Generated by Django 2.2.7 on 2019-12-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0013_auto_20191212_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltests',
            name='client_selected_facility',
            field=models.CharField(choices=[(1, 'Group Home'), (2, 'Secure')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modeltests',
            name='client_selected_level',
            field=models.CharField(choices=[(1, 'Mental Health'), (2, 'Intensive')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
