# Generated by Django 2.2.7 on 2019-12-16 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0014_auto_20191216_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeltests',
            name='client_selected_facility',
        ),
        migrations.RemoveField(
            model_name='modeltests',
            name='client_selected_level',
        ),
        migrations.RemoveField(
            model_name='modeltests',
            name='client_selected_program',
        ),
    ]
