# Generated by Django 2.2.7 on 2019-12-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0016_modeltests_program_model_suggested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeltests',
            name='program_model_suggested',
        ),
        migrations.AddField(
            model_name='adelphoi_mapping',
            name='program_model_suggested',
            field=models.CharField(db_column='program_model_suggested', default=1, max_length=100),
            preserve_default=False,
        ),
    ]
